; Generated by Calypsi ISO C compiler for 6502

            .rtmodel version,"1"
            .rtmodel codeModel,"plain"
            .rtmodel core,"45gs02"
            .rtmodel target,"mega65"
            .extern _AllocStackSave
            .extern _DivMod16
            .extern _Mul16
            .extern _RestoreRegisters
            .extern _UDivMod16
            .extern _Vfp
            .extern _Vsp
            .extern _Zp
            .extern vic4_crosshair
            .extern vic4_panel_char
            .extern vic4_panel_tile
            .extern vic4_puts
            .extern vic4_screen_code
;  #include "panel.h"
;
;  #include "loader.h"
;  #include "vic4.h"
;
;  // Where each readout's digits start. The labels are drawn once by panel_init
;  // and never touched again; only the digits are rewritten each frame.
;  #define ROW_MESSAGE 0
;  #define ROW_FLIGHT  2
;  #define ROW_POS     3
;  #define ROW_STATUS  4
;  #define ROW_CARGO   5
;
;  // The longest thing the bay can be asked to hold. The cargo line is rewritten
;  // when the load is released, so it has to blank whatever the last one left.
;  #define CARGO_WIDTH 12
;
;  // The wind shares the bottom row with the cargo bay, to the right of it and
;  // clear of the overview map, which only reaches down to the row above. The
;  // battery sits directly above the wind, in the space the FPS and speed
;  // readouts leave on their row.
;  #define WIND_COL 20
;  #define BATT_COL 20
;
;  #define ALT_COL 4
;  #define HDG_COL 13
;  #define LAT_COL 4
;  #define LON_COL 17
;  #define FPS_COL 4
;
;  // An angle in 256ths of a turn -- the camera's units, and the wind's -- as the
;  // compass bearing a pilot expects to read.
;  //
;  // The quarter turn is the whole point of it. Angle 0 moves the camera along
;  // +x, which is east, while the overview map is north up, so the raw angle
;  // printed as degrees called east 000 and north 270. Adding 64 first turns it
;  // into a real bearing; the cast back to uint8_t is what wraps 192 (north)
;  // round to 000 rather than letting it read 360.
;  //
;  // 45/32 rather than the equal 360/256: a heading of 183 or more overflows the
;  // 16-bit product of the latter, and 192 came out as 14 degrees.
;  #define DEGREES(a) ((uint16_t)(uint8_t)((a) + 64) * 45 / 32)
;
;  void panel_puts(uint8_t col, uint8_t row, const char *s, uint8_t colour)
;  {
            .section code,text
            .public panel_puts
panel_puts:
            sta     zp:_Zp+4
;    vic4_puts(col, (uint8_t)(FB_ROWS + row), s, colour);
            lda     #19
            clc
            adc     zp:_Zp
            sta     zp:_Zp
            lda     zp:_Zp+4
            jmp     `?L206`
;  }
;
;  // Zero padded rather than space padded, for the fractional half of a
;  // coordinate: .005 of a degree has to read as 005, not as 5.
;  static void put_frac(uint8_t col, uint8_t row, uint16_t value, uint8_t width,
;                       uint8_t colour)
;  {
            .section code,text
put_frac:
            jsr     `?L220`
            sta     zp:_Zp+26
            lda     zp:_Zp+1
            sta     zp:_Zp+27
            lda     zp:_Zp+4
            sta     zp:_Zp+28
;    uint8_t i;
;
;    for (i = width; i-- > 0;) {
            jsr     `?L222`
`?L201`:
;      vic4_panel_char(col + i, row, '0' + (uint8_t)(value % 10), colour);
;      value /= 10;
            sta     zp:_Zp+25
            lda     zp:_Zp+27
            dec     zp:_Zp+27
            tax
            bne     `?L7`
`?L6`:
;    }
;  }
            ldy     #5
            jmp     _RestoreRegisters
`?L7`:
            jsr     `?L207`
            lda     #48
            clc
            adc     zp:_Zp+2
            sta     zp:_Zp+1
            lda     zp:_Zp+28
            sta     zp:_Zp+2
            lda     zp:_Zp+26
            sta     zp:_Zp
            lda     zp:_Zp+27
            clc
            adc     zp:_Zp+29
            jsr     vic4_panel_char
            jsr     `?L207`
            lda     zp:_Zp
            sta     zp:_Zp+24
            lda     zp:_Zp+1
            bra     `?L201`
;
;  // Degrees and three decimals, with the hemisphere letter after them, which is
;  // how a drone controller shows a GPS fix.
;  static void put_degrees(uint8_t col, uint8_t row, uint16_t mdeg, uint8_t width,
;                          char hemisphere)
;  {
            .section code,text
put_degrees:
            jsr     `?L220`
            sta     zp:_Zp+28
            lda     zp:_Zp+1
            sta     zp:_Zp+26
            jsr     `?L222`
            sta     zp:_Zp+25
            lda     zp:_Zp+4
            sta     zp:_Zp+27
;    put_frac(col, row, mdeg / 1000, width, PANEL_INK);
            jsr     `?L209`
            lda     zp:_Zp
            sta     zp:_Zp+2
            lda     zp:_Zp+1
            sta     zp:_Zp+3
            lda     zp:_Zp+26
            sta     zp:_Zp+1
            lda     zp:_Zp+28
            sta     zp:_Zp
            lda     zp:_Zp+29
            jsr     put_frac
;    vic4_panel_char(col + width, row, '.', PANEL_INK);
            jsr     `?L225`
            jsr     `?L214`
            jsr     vic4_panel_char
;    put_frac(col + width + 1, row, mdeg % 1000, 3, PANEL_INK);
            jsr     `?L209`
            lda     #3
            sta     zp:_Zp+1
            jsr     `?L214`
            inc     a
            jsr     put_frac
;    vic4_panel_char(col + width + 4, row, vic4_screen_code(hemisphere), PANEL_INK);
            lda     zp:_Zp+27
            jsr     vic4_screen_code
            sta     zp:_Zp+1
            lda     #1
            sta     zp:_Zp+2
            jsr     `?L214`
            inc     a
            inc     a
            inc     a
            inc     a
            jsr     vic4_panel_char
;  }
            jmp     `?L6`
;
;  // Right-aligned unsigned number, `width` digits, space padded. Returns
;  // nothing: the panel is fixed-width, so there is nowhere for it to overflow
;  // to and a too-large value is clamped to all nines.
;  static void put_number(uint8_t col, uint8_t row, uint16_t value, uint8_t width,
;                         uint8_t colour)
;  {
            .section code,text
put_number: ldx     #0
            ldy     #6
            jsr     _AllocStackSave
            sta     zp:_Zp+30
            lda     zp:_Zp
            sta     zp:_Zp+26
            lda     zp:_Zp+1
            sta     zp:_Zp+28
            lda     zp:_Zp+4
            sta     zp:_Zp+27
;    uint8_t i;
;
;    for (i = width; i-- > 0;) {
            lda     zp:_Zp+28
            sta     zp:_Zp+29
            jsr     `?L222`
`?L204`:
;      uint8_t digit = (uint8_t)(value % 10);
;
;      // Leave a leading zero only in the units position, so 0 reads as "0"
;      // rather than as a blank.
;      if (value == 0 && i != width - 1)
;        vic4_panel_char(col + i, row, ' ', colour);
;      else
;        vic4_panel_char(col + i, row, '0' + digit, colour);
;      value /= 10;
            sta     zp:_Zp+25
            lda     zp:_Zp+29
            dec     zp:_Zp+29
            tax
            bne     `?L17`
;    }
;  }
            ldy     #6
            jmp     _RestoreRegisters
`?L17`:
            jsr     `?L207`
            lda     zp:_Zp+2
            sta     zp:_Zp
            lda     zp:_Zp+24
            ora     zp:_Zp+25
            bne     `?L21`
            lda     zp:_Zp+29
            ldx     zp:_Zp+28
            stx     zp:_Zp+2
            ldx     #0
            stx     zp:_Zp+3
            dew     zp:_Zp+2
            sec
            sbc     zp:_Zp+2
            ora     zp:_Zp+3
            beq     `?L21`
            lda     zp:_Zp+27
            sta     zp:_Zp+2
            lda     #32
            bra     `?L203`
`?L21`:
            lda     zp:_Zp+27
            sta     zp:_Zp+2
            lda     #48
            clc
            adc     zp:_Zp
`?L203`:
            sta     zp:_Zp+1
            lda     zp:_Zp+26
            sta     zp:_Zp
            lda     zp:_Zp+29
            clc
            adc     zp:_Zp+30
            jsr     vic4_panel_char
            jsr     `?L207`
            lda     zp:_Zp
            sta     zp:_Zp+24
            lda     zp:_Zp+1
            bra     `?L204`
;
;  void panel_init(void)
;  {
            .section code,text
            .public panel_init
panel_init: ldx     #0
            ldy     #1
            jsr     _AllocStackSave
;    uint8_t col, row;
;
;    for (row = 0; row < PANEL_ROWS; row++)
            txa
            sta     zp:_Zp+24
`?L28`:
            ldz     _Zp+24
            cpz     #6
            lbcc    `?L27`
            lda     #.byte0 _StringLiteral_ALT
            sta     zp:_Zp+2
            lda     #.byte1 _StringLiteral_ALT
            jsr     `?L208`
            lda     #21
            jsr     `?L213`
            lda     #.byte0 _StringLiteral_HDG
            sta     zp:_Zp+2
            lda     #.byte1 _StringLiteral_HDG
            jsr     `?L208`
            lda     #21
            sta     zp:_Zp
            lda     #9
            jsr     vic4_puts
            lda     #.byte0 _StringLiteral_LAT
            sta     zp:_Zp+2
            lda     #.byte1 _StringLiteral_LAT
            jsr     `?L208`
            lda     #22
            jsr     `?L213`
            lda     #.byte0 _StringLiteral_LON
            sta     zp:_Zp+2
            lda     #.byte1 _StringLiteral_LON
            jsr     `?L208`
            lda     #22
            sta     zp:_Zp
            lda     #13
            jsr     vic4_puts
            lda     #.byte0 _StringLiteral_FPS
            sta     zp:_Zp+2
            lda     #.byte1 _StringLiteral_FPS
            jsr     `?L208`
            lda     #23
            jsr     `?L213`
            lda     #.byte0 _StringLiteral_SPD
            sta     zp:_Zp+2
            lda     #.byte1 _StringLiteral_SPD
            jsr     `?L208`
            lda     #23
            sta     zp:_Zp
            lda     #10
            jsr     vic4_puts
            lda     #.byte0 _StringLiteral_BATT
            sta     zp:_Zp+2
            lda     #.byte1 _StringLiteral_BATT
            jsr     `?L208`
            lda     #23
            jsr     `?L226`
;      for (col = 0; col < PANEL_COLS; col++)
;        vic4_panel_char(col, row, ' ', PANEL_INK);
;
;    panel_puts(0, ROW_FLIGHT, "ALT", PANEL_LABEL);
;    panel_puts(9, ROW_FLIGHT, "HDG", PANEL_LABEL);
;    panel_puts(0, ROW_POS, "LAT", PANEL_LABEL);
;    panel_puts(13, ROW_POS, "LON", PANEL_LABEL);
;    panel_puts(0, ROW_STATUS, "FPS", PANEL_LABEL);
;
;    panel_puts(10, ROW_STATUS, "SPD", PANEL_LABEL);
;
;    panel_puts(BATT_COL, ROW_STATUS, "BATT", PANEL_LABEL);
;    vic4_panel_char(BATT_COL + 8, ROW_STATUS, vic4_screen_code('%'), PANEL_LABEL);
            lda     #37
            jsr     vic4_screen_code
            sta     zp:_Zp+1
            lda     #2
            sta     zp:_Zp+2
            lda     #4
            sta     zp:_Zp
            lda     #28
            jsr     vic4_panel_char
            lda     #.byte0 _StringLiteral_CARGO
            sta     zp:_Zp+2
            lda     #.byte1 _StringLiteral_CARGO
            jsr     `?L208`
            lda     #24
            jsr     `?L213`
            lda     #.byte0 _StringLiteral_WIND
            sta     zp:_Zp+2
            lda     #.byte1 _StringLiteral_WIND
            jsr     `?L208`
            lda     #24
            jsr     `?L226`
            lda     #.byte0 _StringLiteral_DEG
            sta     zp:_Zp+2
            lda     #.byte1 _StringLiteral_DEG
            jsr     `?L208`
            lda     #24
            sta     zp:_Zp
            lda     #28
            jsr     vic4_puts
            lda     #.byte0 `_StringLiteral_M/S`
            sta     zp:_Zp+2
            lda     #.byte1 `_StringLiteral_M/S`
            jsr     `?L208`
            lda     #24
            sta     zp:_Zp
            lda     #34
            jsr     vic4_puts
;
;    panel_puts(0, ROW_CARGO, "CARGO", PANEL_LABEL);
;
;    // Only the two numbers are rewritten when the wind shifts; the units are
;    // part of the furniture, like every other label here.
;    panel_puts(WIND_COL, ROW_CARGO, "WIND", PANEL_LABEL);
;    panel_puts(WIND_COL + 8, ROW_CARGO, "DEG", PANEL_LABEL);
;    panel_puts(WIND_COL + 14, ROW_CARGO, "M/S", PANEL_LABEL);
;
;    // The overview map: full-colour tiles dropped straight into panel cells.
;    // Their pixels came off the disk already in character order, so there is
;    // nothing to do here but name them.
;    //
;    // vic4_overview_ready is NOT called here. This runs again every time a
;    // flight starts, and by then the map carries a crosshair -- taking the
;    // pristine copy from it now would bake that crosshair in permanently. main
;    // takes the copy once, when the map is first loaded.
;    for (row = 0; row < OVERVIEW_CHARS; row++)
            lda     #0
            sta     zp:_Zp+25
`?L36`:
            ldz     _Zp+25
            cpz     #4
            bcc     `?L35`
;      for (col = 0; col < OVERVIEW_CHARS; col++)
;        vic4_panel_tile(PANEL_MAP_COL + col, PANEL_MAP_ROW + row,
;                        (uint16_t)OVERVIEW_CHAR + row * OVERVIEW_CHARS + col);
;  }
            ldy     #1
            jmp     _RestoreRegisters
`?L35`:     lda     #0
            sta     zp:_Zp+24
`?L40`:
            ldz     _Zp+24
            cpz     #4
            bcc     `?L39`
            inc     zp:_Zp+25
            bra     `?L36`
`?L39`:
            ldx     zp:_Zp+25
            stx     zp:_Zp
            lda     #0
            sta     zp:_Zp+1
            asw     _Zp
            asw     _Zp
            lda     zp:_Zp
            clc
            adc     #64
            sta     zp:_Zp+2
            lda     zp:_Zp+1
            adc     #7
            sta     zp:_Zp+3
            clc
            lda     zp:_Zp+2
            adc     zp:_Zp+24
            sta     zp:_Zp+2
            bcc     `?L153`
            inc     zp:_Zp+3
`?L153`:    txa
            sta     zp:_Zp
            inc     zp:_Zp
            lda     #36
            clc
            adc     zp:_Zp+24
            jsr     vic4_panel_tile
            inc     zp:_Zp+24
            bra     `?L40`
`?L27`:     lda     #0
            sta     zp:_Zp+25
`?L32`:
            ldz     _Zp+25
            cpz     #40
            bcc     `?L31`
            inc     zp:_Zp+24
            jmp     `?L28`
`?L31`:
            jsr     `?L217`
            lda     zp:_Zp+24
            sta     zp:_Zp
            tza
            jsr     vic4_panel_char
            inc     zp:_Zp+25
            bra     `?L32`
;
;  // Cinematic / normal / sport, the three a real drone offers.
;  void panel_speed(uint8_t mode)
;  {
            .section code,text
            .public panel_speed
panel_speed:
;    static const char *const names[] = {"SLO", "NRM", "SPT"};
;
;    panel_puts(14, ROW_STATUS, names[mode > 2 ? 2 : mode], PANEL_INK);
            cmp     #3
            bcc     `?L78`
            lda     #2
`?L78`:     asl     a
            tax
            lda     names,x
            sta     zp:_Zp+2
            lda     names+1,x
            sta     zp:_Zp+3
            lda     #1
            sta     zp:_Zp+1
            lda     #23
            sta     zp:_Zp
            lda     #14
`?L206`:
;  }
;
;  void panel_cargo(const char *what)
;  {
;    uint8_t col;
;
;    for (col = 0; col < CARGO_WIDTH; col++)
;      vic4_panel_char((uint8_t)(6 + col), ROW_CARGO, ' ', PANEL_INK);
;    panel_puts(6, ROW_CARGO, what, PANEL_INK);
;  }
;
;  void panel_battery(uint8_t percent)
;  {
;    put_number(BATT_COL + 5, ROW_STATUS, percent, 3, PANEL_INK);
;  }
            jsr     vic4_puts
            rts
            .section cdata,rodata
names:      .word   _StringLiteral_SLO,_StringLiteral_NRM,_StringLiteral_SPT

            .section code,text
            .public panel_cargo
panel_cargo:
            jsr     `?L215`
            txa
            sta     zp:_Zp+26
`?L50`:
            ldz     _Zp+26
            cpz     #12
            bcc     `?L49`
            jsr     `?L218`
            lda     #24
            sta     zp:_Zp
            lda     #6
            jsr     vic4_puts
            ldy     #2
            jmp     _RestoreRegisters
`?L49`:
            jsr     `?L217`
            lda     #5
            sta     zp:_Zp
            lda     #6
            clc
            adc     zp:_Zp+26
            jsr     vic4_panel_char
            inc     zp:_Zp+26
            bra     `?L50`
            .section code,text
            .public panel_battery
panel_battery:
            sta     zp:_Zp
            lda     #1
            sta     zp:_Zp+4
            ldx     zp:_Zp
            stx     zp:_Zp+2
            lda     #0
            jsr     `?L223`
            lda     #4
            sta     zp:_Zp
            lda     #25
            jsr     put_number
            rts
;
;  void panel_wind(uint8_t from, uint8_t mps)
;  {
            .section code,text
            .public panel_wind
panel_wind: ldx     #0
            ldy     #0
            jsr     _AllocStackSave
            ldx     zp:_Zp
            stx     zp:_Zp+24
;    // A bearing is read with its leading zeros -- 045, not 45 -- so this gets
;    // the zero-padded field the coordinates use rather than the space-padded
;    // one the altitude does. Same units as the heading beside it.
;    put_frac(WIND_COL + 5, ROW_CARGO, DEGREES(from), 3, PANEL_INK);
            clc
            adc     #64
            sta     zp:_Zp+2
            ora     #127
            bmi     `?L163`
            lda     #0
`?L163`:
            jsr     `?L211`
            beq     `?L166`
`?L167`:
            lsr     zp:_Zp+3
            ror     zp:_Zp+2
            dex
            bne     `?L167`
`?L166`:    lda     #1
            sta     zp:_Zp+4
            lda     #3
            sta     zp:_Zp+1
            lda     #5
            sta     zp:_Zp
            lda     #25
            jsr     put_frac
;    put_number(WIND_COL + 11, ROW_CARGO, mps, 2, PANEL_INK);
            lda     #1
            sta     zp:_Zp+4
            ldx     zp:_Zp+24
            stx     zp:_Zp+2
            lda     #0
            jsr     `?L208`
            lda     #5
            sta     zp:_Zp
            lda     #31
            jsr     put_number
;  }
            ldy     #0
            jmp     _RestoreRegisters
;
;  void panel_message(const char *s)
;  {
            .section code,text
            .public panel_message
panel_message:
            jsr     `?L215`
;    uint8_t col;
;
;    for (col = 0; col < PANEL_COLS; col++)
            txa
            sta     zp:_Zp+26
`?L63`:
            ldz     _Zp+26
            cpz     #40
            bcc     `?L62`
            jsr     `?L218`
            lda     #19
            jsr     `?L213`
;      vic4_panel_char(col, ROW_MESSAGE, ' ', PANEL_INK);
;    panel_puts(0, ROW_MESSAGE, s, PANEL_INK);
;  }
            ldy     #2
            jmp     _RestoreRegisters
`?L62`:
            jsr     `?L217`
            lda     #0
            sta     zp:_Zp
            tza
            jsr     vic4_panel_char
            inc     zp:_Zp+26
            bra     `?L63`
;
;  void panel_status(int16_t altitude, uint8_t heading, uint16_t x, uint16_t y,
;                    uint16_t fps10)
;  {
            .section code,text
            .public panel_status
panel_status:
            ldx     #0
            ldy     #4
            jsr     _AllocStackSave
            sta     zp:_Zp+26
            lda     zp:_Zp+6
            sta     zp:_Zp+24
            lda     zp:_Zp+7
            sta     zp:_Zp+25
;    uint8_t cx = (uint8_t)(x >> 8);  // the map cell, and one millidegree
            lda     zp:_Zp+3
            sta     zp:_Zp+28
;    uint8_t cy = (uint8_t)(y >> 8);
            lda     zp:_Zp+5
            sta     zp:_Zp+27
;
;    if (altitude < 0)
            lda     zp:_Zp+1
            bpl     `?L70`
;      altitude = 0;
            txa
            sta     zp:_Zp
            sta     zp:_Zp+1
`?L70`:
;
;    put_number(ALT_COL, ROW_FLIGHT, (uint16_t)altitude, 3, PANEL_INK);
            lda     #1
            sta     zp:_Zp+4
            lda     zp:_Zp
            sta     zp:_Zp+2
            lda     zp:_Zp+1
            jsr     `?L223`
            lda     #2
            sta     zp:_Zp
            lda     #4
            jsr     put_number
;    put_number(HDG_COL, ROW_FLIGHT, DEGREES(heading), 3, PANEL_INK);
            lda     #64
            clc
            adc     zp:_Zp+26
            sta     zp:_Zp+2
            ora     #127
            bmi     `?L176`
            lda     #0
`?L176`:
            jsr     `?L211`
            beq     `?L179`
`?L180`:
            lsr     zp:_Zp+3
            ror     zp:_Zp+2
            dex
            bne     `?L180`
`?L179`:    lda     #1
            sta     zp:_Zp+4
            lda     #3
            sta     zp:_Zp+1
            lda     #2
            sta     zp:_Zp
            lda     #13
            jsr     put_number
;
;    put_degrees(LAT_COL, ROW_POS, MAP_LAT_SOUTH + (255 - cy), 2, 'N');
            lda     #255
            sta     zp:_Zp
            lda     #0
            sta     zp:_Zp+1
            sec
            lda     zp:_Zp
            sbc     zp:_Zp+27
            sta     zp:_Zp
            bcs     `?L183`
            dec     zp:_Zp+1
`?L183`:    lda     #78
            sta     zp:_Zp+4
            lda     zp:_Zp
            clc
            adc     #164
            sta     zp:_Zp+2
            lda     zp:_Zp+1
            adc     #181
            jsr     `?L208`
            lda     #3
            sta     zp:_Zp
            lda     #4
            jsr     put_degrees
;    put_degrees(LON_COL, ROW_POS, MAP_LON_WEST + cx, 3, 'E');
            lda     #69
            sta     zp:_Zp+4
            lda     zp:_Zp+28
            clc
            adc     #64
            sta     zp:_Zp+2
            lda     #0
            adc     #31
            jsr     `?L223`
            sta     zp:_Zp
            lda     #17
            jsr     put_degrees
;
;    // The overview is one pixel per eight cells, so the cell index shifts
;    // straight down into it.
;    vic4_crosshair((uint8_t)(cx * OVERVIEW_PX / 256),
            ldx     zp:_Zp+28
            jsr     `?L224`
            beq     `?L187`
`?L188`:
            asw     _Zp
            dex
            bne     `?L188`
`?L187`:
            jsr     `?L219`
            lda     zp:_Zp
            sta     zp:_Zp+4
            ldx     zp:_Zp+27
            jsr     `?L224`
            beq     `?L191`
`?L192`:
            asw     _Zp
            dex
            bne     `?L192`
`?L191`:
            jsr     `?L219`
            lda     zp:_Zp+4
            jsr     vic4_crosshair
;                   (uint8_t)(cy * OVERVIEW_PX / 256));
;
;    if (fps10 > 999)
            lda     #231
            cmp     zp:_Zp+24
            lda     #3
            sbc     zp:_Zp+25
            bcs     `?L73`
;      fps10 = 999;
            lda     #231
            sta     zp:_Zp+24
            lda     #3
            sta     zp:_Zp+25
`?L73`:
;    put_number(FPS_COL, ROW_STATUS, fps10 / 10, 2, PANEL_INK);
            jsr     `?L207`
            lda     #1
            sta     zp:_Zp+4
            lda     zp:_Zp
            sta     zp:_Zp+2
            lda     zp:_Zp+1
            jsr     `?L208`
            lda     #4
            sta     zp:_Zp
            jsr     put_number
;    vic4_panel_char(FPS_COL + 2, ROW_STATUS, '.', PANEL_INK);
            jsr     `?L225`
            lda     #4
            sta     zp:_Zp
            lda     #6
            jsr     vic4_panel_char
;    put_number(FPS_COL + 3, ROW_STATUS, fps10 % 10, 1, PANEL_INK);
            jsr     `?L207`
            lda     #1
            sta     zp:_Zp+4
            sta     zp:_Zp+1
            lda     #4
            sta     zp:_Zp
            lda     #7
            jsr     put_number
;  }
            ldy     #4
            jmp     _RestoreRegisters
            .section code,text
`?L207`:
            lda     zp:_Zp+24
            sta     zp:_Zp
            lda     zp:_Zp+25
            sta     zp:_Zp+1
            lda     #10
            sta     zp:_Zp+10
            lda     #0
            sta     zp:_Zp+11
            jmp     _UDivMod16
            .section code,text
`?L208`:
            sta     zp:_Zp+3
            lda     #2
            sta     zp:_Zp+1
            rts
            .section code,text
`?L209`:
            lda     zp:_Zp+24
            sta     zp:_Zp
            lda     zp:_Zp+25
            sta     zp:_Zp+1
            lda     #232
            sta     zp:_Zp+10
            lda     #3
            sta     zp:_Zp+11
            jsr     _UDivMod16
            lda     #1
            sta     zp:_Zp+4
            rts
            .section code,text
`?L211`:
            sta     zp:_Zp+3
            lda     #45
            sta     zp:_Zp
            lda     #0
            sta     zp:_Zp+1
            jsr     _Mul16
            lda     zp:_Zp
            sta     zp:_Zp+2
            lda     zp:_Zp+1
            sta     zp:_Zp+3
            ldx     #5
            rts
            .section code,text
`?L213`:
            sta     zp:_Zp
            lda     #0
            jmp     vic4_puts
            .section code,text
`?L214`:
            lda     zp:_Zp+28
            sta     zp:_Zp
            lda     zp:_Zp+26
            clc
            adc     zp:_Zp+29
            rts
            .section code,text
`?L215`:    ldx     #0
            ldy     #2
            jsr     _AllocStackSave
            lda     zp:_Zp
            sta     zp:_Zp+24
            lda     zp:_Zp+1
            sta     zp:_Zp+25
            rts
            .section code,text
`?L217`:    lda     #1
            sta     zp:_Zp+2
            lda     #32
            sta     zp:_Zp+1
            rts
            .section code,text
`?L218`:
            lda     zp:_Zp+24
            sta     zp:_Zp+2
            lda     zp:_Zp+25
            sta     zp:_Zp+3
            lda     #1
            sta     zp:_Zp+1
            rts
            .section code,text
`?L219`:    lda     #0
            sta     zp:_Zp+10
            lda     #1
            sta     zp:_Zp+11
            jmp     _DivMod16
            .section code,text
`?L220`:    ldx     #0
            ldy     #5
            jsr     _AllocStackSave
            sta     zp:_Zp+29
            lda     zp:_Zp
            rts
            .section code,text
`?L222`:
            lda     zp:_Zp+2
            sta     zp:_Zp+24
            lda     zp:_Zp+3
            rts
            .section code,text
`?L223`:
            sta     zp:_Zp+3
            lda     #3
            sta     zp:_Zp+1
            rts
            .section code,text
`?L224`:
            stx     zp:_Zp
            lda     #0
            sta     zp:_Zp+1
            lda     #5
            tax
            rts
            .section code,text
`?L225`:    lda     #1
            sta     zp:_Zp+2
            lda     #46
            sta     zp:_Zp+1
            rts
            .section code,text
`?L226`:
            sta     zp:_Zp
            lda     #20
            jmp     vic4_puts
            .section cdata,rodata
            .pubweak _StringLiteral_ALT
_StringLiteral_ALT:
            .byte   65,76,84,0
            .section cdata,rodata
            .pubweak _StringLiteral_BATT
_StringLiteral_BATT:
            .byte   66,65,84,84,0

            .section cdata,rodata
            .pubweak _StringLiteral_CARGO
_StringLiteral_CARGO:
            .byte   67,65,82,71,79,0

            .section cdata,rodata
            .pubweak _StringLiteral_DEG
_StringLiteral_DEG:
            .byte   68,69,71,0
            .section cdata,rodata
            .pubweak _StringLiteral_FPS
_StringLiteral_FPS:
            .byte   70,80,83,0
            .section cdata,rodata
            .pubweak _StringLiteral_HDG
_StringLiteral_HDG:
            .byte   72,68,71,0
            .section cdata,rodata
            .pubweak _StringLiteral_LAT
_StringLiteral_LAT:
            .byte   76,65,84,0
            .section cdata,rodata
            .pubweak _StringLiteral_LON
_StringLiteral_LON:
            .byte   76,79,78,0
            .section cdata,rodata
            .pubweak `_StringLiteral_M/S`
`_StringLiteral_M/S`:
            .byte   77,47,83,0
            .section cdata,rodata
            .pubweak _StringLiteral_NRM
_StringLiteral_NRM:
            .byte   78,82,77,0
            .section cdata,rodata
            .pubweak _StringLiteral_SLO
_StringLiteral_SLO:
            .byte   83,76,79,0
            .section cdata,rodata
            .pubweak _StringLiteral_SPD
_StringLiteral_SPD:
            .byte   83,80,68,0
            .section cdata,rodata
            .pubweak _StringLiteral_SPT
_StringLiteral_SPT:
            .byte   83,80,84,0
            .section cdata,rodata
            .pubweak _StringLiteral_WIND
_StringLiteral_WIND:
            .byte   87,73,78,68,0


