#!/usr/bin/env python3
"""Emit the colour pass's two lookup tables as C, from tools/fixed.py.

The generator's transcendentals are 257-entry tables with linear interpolation
between the entries -- see the module docstring in tools/fixed.py for why.
Two of them cannot be derived on the machine the way the square root can: the
ramp's gamma wants a fractional power and the sun's tanh wants an exponential.
So they are generated here and compiled in.

**Generated, not typed.** They come out of `fixed.py`'s own tables, so a change
to the gamma or the tanh limit reaches the device by rebuilding rather than by
somebody remembering. `make` runs this whenever fixed.py is newer than the
header.

    python3 tools/mktables.py src/mapgen/tables.h
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import fixed as F  # noqa: E402
import genmap as g  # noqa: E402


def emit(f, name, values, ctype):
    f.write(f"static const {ctype} {name}[{len(values)}] = {{\n")
    for i in range(0, len(values), 8):
        row = ", ".join(f"{int(v)}UL" if ctype == "uint32_t" else f"{int(v)}"
                        for v in values[i:i + 8])
        f.write(f"  {row},\n")
    f.write("};\n\n")


def main():
    out = sys.argv[1]
    with open(out, "w") as f:
        f.write("// Generated by tools/mktables.py from tools/fixed.py -- do\n"
                "// not edit. The colour pass's two tables: the land ramp's\n"
                "// gamma and the sun's tanh, 257 entries each, read at eight\n"
                "// bits with the rest interpolated.\n"
                "#ifndef MAPGEN_TABLES_H\n"
                "#define MAPGEN_TABLES_H\n\n"
                "#include <stdint.h>\n\n"
                "// **32-bit, and that is not caution.** The ramp's input runs\n"
                "// past 1.0 -- it is a height over the map's own 99th\n"
                "// percentile -- so the table is read over 0..2 and its top\n"
                "// entry is 2^1.8, which is three and a half times ONE.\n")
        emit(f, "gamma_tab", g.GAMMA, "uint32_t")
        f.write("// tanh over 0..%d, odd about zero, so only one side is kept.\n"
                % F.TANH_LIMIT)
        emit(f, "tanh_tab", F.TANH, "uint16_t")
        f.write("#endif\n")
    print(f"{out}: gamma {len(g.GAMMA)} entries, tanh {len(F.TANH)}")


if __name__ == "__main__":
    main()
